#!/bin/ksh

params=$(awk "NR==$SGE_TASK_ID" forkintegrate.params)

image1=`echo $params | awk '{print $1}'`
nitask=`echo $params | awk '{print $2}'`
itask=`echo $params | awk '{print $3}'`
nbatask=`echo $params | awk '{print $4}'`

host=`uname -a | awk '{print $2}'`
echo $image1 $nitask $itask $nbatask $host $JOB_ID >> jobs.log
date >> .${itask}.dat
ps -ef | grep -v '^root' >> .${itask}.dat
echo '=========' >> .${itask}.dat
echo $host >> .${itask}.dat
cat /proc/cpuinfo | grep 'cpu MHz' | sort | uniq >> .${itask}.dat
cat /proc/cpuinfo | grep processor | wc -l >> .${itask}.dat
uptime >> .${itask}.dat
free >> .${itask}.dat
echo $JOB_ID >> .${itask}.dat
echo $image1 $nitask $itask $nbatask | mintegrate_par
echo "BEAMLINE is" ${BEAMLINE} >> .${itask}.dat
date >> .${itask}.dat
cat /proc/cpuinfo | grep 'cpu MHz' | sort | uniq >> .${itask}.dat

